// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    int32_t capacity;
    int32_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, const uint8_t *_Nonnull, int32_t, RustBuffer *_Nonnull);

// Task defined in Rust that Swift executes
typedef void (*UniFfiRustTaskCallback)(const void * _Nullable, int8_t);

// Callback to execute Rust tasks using a Swift Task
//
// Args:
//   executor: ForeignExecutor lowered into a size_t value
//   delay: Delay in MS
//   task: UniFfiRustTaskCallback to call
//   task_data: data to pass the task callback
typedef int8_t (*UniFfiForeignExecutorCallback)(size_t, uint32_t, UniFfiRustTaskCallback _Nullable, const void * _Nullable);

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Continuation callback for UniFFI Futures
typedef void (*UniFfiRustFutureContinuation)(void * _Nonnull, int8_t);

// Scaffolding functions
void uniffi_uniffi_callback_demo_fn_free_callbackservice(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_uniffi_callback_demo_fn_constructor_callbackservice_new(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_callbackservice_call_add_two_numbers(void*_Nonnull ptr, int32_t a, int32_t b, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_callbackservice_get_status(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_callbackservice_process_data(void*_Nonnull ptr, RustBuffer data, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_method_callbackservice_simulate_background_work(void*_Nonnull ptr, uint32_t duration_seconds, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_method_callbackservice_trigger_event(void*_Nonnull ptr, RustBuffer event_type, RustBuffer message, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_free_dataprocessingservice(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_uniffi_callback_demo_fn_constructor_dataprocessingservice_new(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_dataprocessingservice_batch_transform(void*_Nonnull ptr, RustBuffer data, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_dataprocessingservice_get_processor_info(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_dataprocessingservice_process_single_item(void*_Nonnull ptr, RustBuffer item, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_method_dataprocessingservice_set_processor(void*_Nonnull ptr, uint32_t processor_id, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_dataprocessingservice_validate_and_process(void*_Nonnull ptr, RustBuffer input, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_free_storageservice(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_uniffi_callback_demo_fn_constructor_storageservice_new(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_storageservice_backup_multiple_keys(void*_Nonnull ptr, RustBuffer keys, RustBuffer backup_key, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_storageservice_copy_data(void*_Nonnull ptr, RustBuffer source_key, RustBuffer target_key, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_storageservice_read_data(void*_Nonnull ptr, RustBuffer key, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_method_storageservice_set_client(void*_Nonnull ptr, uint32_t client_id, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_storageservice_write_data(void*_Nonnull ptr, RustBuffer key, RustBuffer value, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_free_userservice(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_uniffi_callback_demo_fn_constructor_userservice_new(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_userservice_calculate_user_score(void*_Nonnull ptr, uint32_t user_id, RustBuffer metrics, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_userservice_get_user(void*_Nonnull ptr, uint32_t user_id, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_method_userservice_send_notification(void*_Nonnull ptr, uint32_t user_id, RustBuffer message, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_method_userservice_set_manager(void*_Nonnull ptr, uint32_t manager_id, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_userservice_update_user_preferences(void*_Nonnull ptr, uint32_t user_id, RustBuffer preferences, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_free_websocketservice(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_uniffi_callback_demo_fn_constructor_websocketservice_new(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_websocketservice_ping_pong(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_websocketservice_read_message(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_websocketservice_send_and_read(void*_Nonnull ptr, RustBuffer message, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_websocketservice_send_batch_messages(void*_Nonnull ptr, RustBuffer messages, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_method_websocketservice_send_message(void*_Nonnull ptr, RustBuffer message, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_method_websocketservice_set_client(void*_Nonnull ptr, uint32_t client_id, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_init_callback_dataprocessor(ForeignCallback _Nonnull callback_stub, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_init_callback_eventcallback(ForeignCallback _Nonnull callback_stub, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_init_callback_storageclient(ForeignCallback _Nonnull callback_stub, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_init_callback_userprofilemanager(ForeignCallback _Nonnull callback_stub, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_init_callback_websocketclient(ForeignCallback _Nonnull callback_stub, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_func_create_test_data(uint32_t size, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_uniffi_callback_demo_fn_func_format_message(RustBuffer prefix, RustBuffer content, RustCallStatus *_Nonnull out_status
);
uint32_t uniffi_uniffi_callback_demo_fn_func_register_callback(uint64_t callback, RustCallStatus *_Nonnull out_status
);
uint32_t uniffi_uniffi_callback_demo_fn_func_register_data_processor(uint64_t processor, RustCallStatus *_Nonnull out_status
);
uint32_t uniffi_uniffi_callback_demo_fn_func_register_storage_client(uint64_t client, RustCallStatus *_Nonnull out_status
);
uint32_t uniffi_uniffi_callback_demo_fn_func_register_user_manager(uint64_t manager, RustCallStatus *_Nonnull out_status
);
uint32_t uniffi_uniffi_callback_demo_fn_func_register_websocket_client(uint64_t client, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_func_set_service_callback(void*_Nonnull service, uint32_t callback_id, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_func_unregister_callback(uint32_t callback_id, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_func_unregister_data_processor(uint32_t processor_id, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_func_unregister_storage_client(uint32_t client_id, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_func_unregister_user_manager(uint32_t manager_id, RustCallStatus *_Nonnull out_status
);
void uniffi_uniffi_callback_demo_fn_func_unregister_websocket_client(uint32_t client_id, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_uniffi_callback_demo_rustbuffer_alloc(int32_t size, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_uniffi_callback_demo_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
void ffi_uniffi_callback_demo_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_uniffi_callback_demo_rustbuffer_reserve(RustBuffer buf, int32_t additional, RustCallStatus *_Nonnull out_status
);
void ffi_uniffi_callback_demo_rust_future_continuation_callback_set(UniFfiRustFutureContinuation _Nonnull callback
);
void ffi_uniffi_callback_demo_rust_future_poll_u8(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_uniffi_callback_demo_rust_future_cancel_u8(void* _Nonnull handle
);
void ffi_uniffi_callback_demo_rust_future_free_u8(void* _Nonnull handle
);
uint8_t ffi_uniffi_callback_demo_rust_future_complete_u8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_uniffi_callback_demo_rust_future_poll_i8(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_uniffi_callback_demo_rust_future_cancel_i8(void* _Nonnull handle
);
void ffi_uniffi_callback_demo_rust_future_free_i8(void* _Nonnull handle
);
int8_t ffi_uniffi_callback_demo_rust_future_complete_i8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_uniffi_callback_demo_rust_future_poll_u16(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_uniffi_callback_demo_rust_future_cancel_u16(void* _Nonnull handle
);
void ffi_uniffi_callback_demo_rust_future_free_u16(void* _Nonnull handle
);
uint16_t ffi_uniffi_callback_demo_rust_future_complete_u16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_uniffi_callback_demo_rust_future_poll_i16(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_uniffi_callback_demo_rust_future_cancel_i16(void* _Nonnull handle
);
void ffi_uniffi_callback_demo_rust_future_free_i16(void* _Nonnull handle
);
int16_t ffi_uniffi_callback_demo_rust_future_complete_i16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_uniffi_callback_demo_rust_future_poll_u32(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_uniffi_callback_demo_rust_future_cancel_u32(void* _Nonnull handle
);
void ffi_uniffi_callback_demo_rust_future_free_u32(void* _Nonnull handle
);
uint32_t ffi_uniffi_callback_demo_rust_future_complete_u32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_uniffi_callback_demo_rust_future_poll_i32(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_uniffi_callback_demo_rust_future_cancel_i32(void* _Nonnull handle
);
void ffi_uniffi_callback_demo_rust_future_free_i32(void* _Nonnull handle
);
int32_t ffi_uniffi_callback_demo_rust_future_complete_i32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_uniffi_callback_demo_rust_future_poll_u64(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_uniffi_callback_demo_rust_future_cancel_u64(void* _Nonnull handle
);
void ffi_uniffi_callback_demo_rust_future_free_u64(void* _Nonnull handle
);
uint64_t ffi_uniffi_callback_demo_rust_future_complete_u64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_uniffi_callback_demo_rust_future_poll_i64(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_uniffi_callback_demo_rust_future_cancel_i64(void* _Nonnull handle
);
void ffi_uniffi_callback_demo_rust_future_free_i64(void* _Nonnull handle
);
int64_t ffi_uniffi_callback_demo_rust_future_complete_i64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_uniffi_callback_demo_rust_future_poll_f32(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_uniffi_callback_demo_rust_future_cancel_f32(void* _Nonnull handle
);
void ffi_uniffi_callback_demo_rust_future_free_f32(void* _Nonnull handle
);
float ffi_uniffi_callback_demo_rust_future_complete_f32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_uniffi_callback_demo_rust_future_poll_f64(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_uniffi_callback_demo_rust_future_cancel_f64(void* _Nonnull handle
);
void ffi_uniffi_callback_demo_rust_future_free_f64(void* _Nonnull handle
);
double ffi_uniffi_callback_demo_rust_future_complete_f64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_uniffi_callback_demo_rust_future_poll_pointer(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_uniffi_callback_demo_rust_future_cancel_pointer(void* _Nonnull handle
);
void ffi_uniffi_callback_demo_rust_future_free_pointer(void* _Nonnull handle
);
void*_Nonnull ffi_uniffi_callback_demo_rust_future_complete_pointer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_uniffi_callback_demo_rust_future_poll_rust_buffer(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_uniffi_callback_demo_rust_future_cancel_rust_buffer(void* _Nonnull handle
);
void ffi_uniffi_callback_demo_rust_future_free_rust_buffer(void* _Nonnull handle
);
RustBuffer ffi_uniffi_callback_demo_rust_future_complete_rust_buffer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_uniffi_callback_demo_rust_future_poll_void(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_uniffi_callback_demo_rust_future_cancel_void(void* _Nonnull handle
);
void ffi_uniffi_callback_demo_rust_future_free_void(void* _Nonnull handle
);
void ffi_uniffi_callback_demo_rust_future_complete_void(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
uint16_t uniffi_uniffi_callback_demo_checksum_func_create_test_data(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_func_format_message(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_func_register_callback(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_func_register_data_processor(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_func_register_storage_client(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_func_register_user_manager(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_func_register_websocket_client(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_func_set_service_callback(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_func_unregister_callback(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_func_unregister_data_processor(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_func_unregister_storage_client(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_func_unregister_user_manager(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_func_unregister_websocket_client(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_callbackservice_call_add_two_numbers(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_callbackservice_get_status(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_callbackservice_process_data(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_callbackservice_simulate_background_work(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_callbackservice_trigger_event(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_dataprocessingservice_batch_transform(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_dataprocessingservice_get_processor_info(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_dataprocessingservice_process_single_item(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_dataprocessingservice_set_processor(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_dataprocessingservice_validate_and_process(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_storageservice_backup_multiple_keys(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_storageservice_copy_data(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_storageservice_read_data(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_storageservice_set_client(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_storageservice_write_data(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_userservice_calculate_user_score(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_userservice_get_user(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_userservice_send_notification(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_userservice_set_manager(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_userservice_update_user_preferences(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_websocketservice_ping_pong(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_websocketservice_read_message(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_websocketservice_send_and_read(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_websocketservice_send_batch_messages(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_websocketservice_send_message(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_websocketservice_set_client(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_constructor_callbackservice_new(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_constructor_dataprocessingservice_new(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_constructor_storageservice_new(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_constructor_userservice_new(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_constructor_websocketservice_new(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_dataprocessor_process_item(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_dataprocessor_validate_input(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_dataprocessor_transform_data(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_dataprocessor_get_processor_name(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_eventcallback_on_event(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_eventcallback_on_data_received(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_eventcallback_add_two_numbers(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_storageclient_read(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_storageclient_write(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_userprofilemanager_get_user_info(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_userprofilemanager_update_preferences(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_userprofilemanager_calculate_score(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_userprofilemanager_notify_user(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_websocketclient_send(void
    
);
uint16_t uniffi_uniffi_callback_demo_checksum_method_websocketclient_read(void
    
);
uint32_t ffi_uniffi_callback_demo_uniffi_contract_version(void
    
);

